### ISSUE TITLE
Performance impact: 30% reduction

### ISSUE THREAD

**Issue by rohitjoshi** [tshlabs/cadence#83] opened 2019-03-05 22:15 UTC
Thank you for implementing `DataDog` compliant `statsd` client.   When I enabled metrics, I see a reduction in the performance by ~30%.

I am using `./dogstatsd-local -host 127.0.0.1 -port 8125 &> /dev/null` as a server agent.

Here is code to create a client:

```
    let socket = match UdpSocket::bind("0.0.0.0:0") {
                Ok(s) => { s },
                Err(e) => {
                    error!("UdpSocket bind failed. Error:{:?}", e);
                    return Err(e.to_string());
                }
            };
            if let Err(e) = socket.set_nonblocking(true) {
                return Err(e.to_string());
            }

            let host = (conf.host.as_str(), conf.port);
            let udp_sink = match BufferedUdpMetricSink:: with_capacity(host, socket, 1024*1024) {
                Ok(s) => { s },
                Err(e) => {
                    return Err(e.to_string());
                }
            };
            let queuing_sink = QueuingMetricSink::from(udp_sink);
            let client = StatsdClient::from_sink(&conf.prefix, queuing_sink);
```

```
#[inline]
    pub fn incr<'a>(&'a self, name: &'a str)  {
        if self.conf.enabled {
            debug!("metrics:incr: {}", name);
            let _ = self.get_client().incr_with_tags(name).try_send();
        }
    }
    #[inline]
    pub fn decr<'a>(&'a self, name: &'a str)  {
        if self.conf.enabled {
            debug!("metrics:incr: {}", name);
            let _ = self.get_client().decr_with_tags(name).try_send();
        }
    }

 #[inline]
    pub fn timed_fn_db<'a, F, R>(&'a self, table_name: &'a [u8], operation: &'a str, callable: F) -> R
        where F: FnOnce() -> R
    {
        if self.conf.enabled {
            let start = time::Instant::now();
            let return_val = callable();
            let used = start.elapsed();
            let metric = format!("{}.{}", String::from_utf8_lossy(&table_name),operation);
            debug!("metrics:timed_fn_db: {}, Time:{:?}", metric, used);
            let _ = self.get_client().time_duration_with_tags(&metric, used).try_send();
            return_val
        }else {
            callable()
        }
    }
```

Code is compiled in the release mode:
```
[profile.release]
opt-level = 3
lto = true
```

Am I missing anything?

**Comment by 56quarters** [comment] 2019-03-06 00:32
Hi @rohitjoshi,

The way you've created the client looks correct (using the buffered UDP sink with the queuing sink).

Your code example looks like it's part of a larger program. Is there a self-contained test case you could share the reproduces the issue? Or perhaps more concrete numbers. I'm don't know what "40%" is out of.

In the Cadence benchmarks for version 0.16.0, I typically see calls to emit tagged metrics with the `QueuingMetricSink` take about 700 nano seconds.

Cadence 0.16.0
```
test test_benchmark_statsdclient_queuing_nop            ... bench:         459 ns/iter (+/- 27)
test test_benchmark_statsdclient_queuing_nop_with_tags  ... bench:         690 ns/iter (+/- 26)
```

With Cadence 0.17.0 (not released yet), that drops a bit:
```
test test_benchmark_statsdclient_queuing_nop                    ... bench:         336 ns/iter (+/- 102)
test test_benchmark_statsdclient_queuing_nop_with_tags          ... bench:         375 ns/iter (+/- 27)
```

Testing out some benchmarks of code similar to what you posted, many of the calls can easily take the same about of time as Cadence itself.

```
test test_benchmark_demo_format                                 ... bench:          44 ns/iter (+/- 9)
test test_benchmark_demo_log_debug                              ... bench:         828 ns/iter (+/- 205)
test test_benchmark_demo_time_instant                           ... bench:         811 ns/iter (+/- 61)
```

The code for the functions I'm testing is:
```rust
#[bench]
fn test_benchmark_demo_format(b: &mut Bencher) {
    let mut v = 0;
    b.iter(|| {
        let s = format!("something: {}", v);
        v += 1;
    });
}

#[bench]
fn test_benchmark_demo_log_debug(b: &mut Bencher) {
    env_logger::init();

    let mut v = 0;
    b.iter(|| {
        debug!("Something going on: {:?}", v);
        v += 1;
    });
}

#[bench]
fn test_benchmark_demo_time_instant(b: &mut Bencher) {
    use std::time;

    fn do_some_work() {
        // not really!
    }

    b.iter(|| {
        let start = time::Instant::now();
        do_some_work();
        let used  = start.elapsed();

        debug!("Took some time: {:?}", used);
    });
}
```

This doesn't include whatever the callback in your example was doing (obviously).

Without more information I can't really say where the issue is, but it doesn't seem like this is a performance problem with Cadence to me. Thanks!

**Comment by rohitjoshi** [comment] 2019-03-06 00:54
Thanks.  My application writes to RocksDB. Every `put` and `get` operation, multiple statsd metrics generated.

e.g Every get function includes 1 timed function and 2-3 increment operations.

```
#[inline]
    fn on_cmd_get(&self,db: &[u8], key: &[u8])->Result<Vec<u8>,String>{
        self.stats.incr("redis.get");
        match **self.get(&db, &key)** {
            Ok((val, cache_status)) => {
                self.stats.incr("db.get");
                if cache_status {
                    self.stats.incr("db.get.cache");
                }
                Ok(val)
            },
            Err(e) => {
                self.stats.incr("db.get.notfound");
                Err(e.to_string())
            }
        }
    }

 #[inline]
    pub fn **get**(&self, table_name: &[u8], key: &[u8]) -> Result<(Vec<u8>, bool), String>{
        self.stats.timed_fn_db(&table_name, "get", || {

            let kv = KeyVal::new_with_db_key(&table_name, &key);
            self.db.get(&kv)
            
        })
    }
```

**Comment by rohitjoshi** [comment] 2019-03-06 00:59
NOTE:  `debug!()` macros will be removed at the compile time as I use `slog` with `release` max level as `info`
```
[dependencies.slog]
version = "2.4.1"
features = ["max_level_debug", "release_max_level_info"]
```

**Comment by 56quarters** [comment] 2019-03-06 01:44
I'm not in a great position to debug this, but it sounds like `gets` and `puts` to RocksDB are very fast and so metrics are a non-trivial amount of time for each operation.

You could try using the latest commit of Cadence (which hasn't been released yet) instead of 0.16.0 and see if it is faster: f4fddc2695429adee2fcc01a6ed2fdf5f94302d6

**Comment by rohitjoshi** [comment] 2019-03-06 04:02
Thx.

**Comment by 56quarters** [comment] 2019-03-07 23:06
Seems like there isn't anything particularly wrong with Cadence so I'm going to close this issue and eventually release 0.17.0 which will help a bit.

**Closed by 56quarters** 2019-03-07 23:06 UTC
